### PR TITLE
feat: set queue as an attribute on poller

### PR DESCRIPTION
**Pull request by sloria**

### CODE REVIEW

**Comment by sloria** [comment]
Just opening this to start discussion on the feature I'm working on. I need to have one handler execute after the completion of another handler after some configurable delay. The thought here is that I could call `poller.queue.send_message(...., DelaySeconds=delay)` from the first handler. @taion wdyt?

**Comment by taion** [comment]
oh, that's neat. cc @itajaja wdyt?

it's a little different because there's no SNS-ish mapping here, but maybe that's okay?

can't think of another good way to accomplish this

**Comment by itajaja** [comment]
why not doing it the normal route, that is publishing it on sns? is the delay the problem? probably would still occupy the thread if you do `time.sleep(d); topic.publish` right?

**Comment by itajaja** [comment]
this pr is rather innocusous so I am ok merging it, although it breaks the abstraction a little

**Comment by taion** [comment]
delaying is no good b/c you need to delete the first queue message

**Comment by sloria** [comment]
OK, going ahead with this for now.

**Comment by itajaja** [comment]
> delaying is no good b/c you need to delete the first queue message

can you clarify what you mean? Just curious about the use case here :)

**Comment by taion** [comment]
if you put a time.sleep(500) in there, then SQS will think the queue worker died

**Comment by itajaja** [comment]
[nope :)](https://github.com/4Catalyzer/tqp/blob/master/tqp/topic_queue_poller.py#L150)

**Comment by taion** [comment]
ahh, forgot about that

**Pull request merged**
